import { Link } from "wouter";
import { Button } from "@/components/ui/button";

function TermsNavbar() {
  return (
    <nav className="fixed top-0 w-full z-50 bg-background/80 backdrop-blur-md border-b border-border">
      <div className="max-w-7xl mx-auto flex items-center justify-between px-6 h-14">
        <Link href="/">
          <div className="flex items-center gap-2 cursor-pointer">
            <div className="w-6 h-6 rounded bg-primary flex items-center justify-center">
              <span className="text-primary-foreground font-bold text-xs">K</span>
            </div>
            <span className="font-display text-sm tracking-[0.3em] text-foreground">K L A U Z A</span>
          </div>
        </Link>
        <div className="hidden md:flex items-center gap-6">
          <Link href="/about" className="text-sm text-muted-foreground hover:text-foreground transition-colors">About</Link>
          <Link href="/blog" className="text-sm text-muted-foreground hover:text-foreground transition-colors">Blog</Link>
          <Link href="/contact" className="text-sm text-muted-foreground hover:text-foreground transition-colors">Contact</Link>
        </div>
        <Link href="/auth">
          <Button className="rounded-full bg-foreground text-background hover:bg-foreground/90 text-sm px-5 h-9">
            Start Free
          </Button>
        </Link>
      </div>
    </nav>
  );
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background" data-testid="terms-page">
      <TermsNavbar />

      <main className="pt-28 pb-20 px-6">
        <div className="max-w-3xl mx-auto">
          <p className="text-xs font-display tracking-widest text-primary uppercase mb-3">Legal</p>
          <h1 className="font-display text-3xl sm:text-4xl uppercase leading-tight mb-2">
            TERMS OF <span className="text-primary">SERVICE</span>
          </h1>
          <p className="text-sm text-muted-foreground mb-10">Effective Date: March 1, 2026</p>

          <div className="prose-sm space-y-8">
            <section>
              <h2 className="font-display text-sm uppercase tracking-wider text-foreground mb-3">1. Acceptance of Terms</h2>
              <p className="text-sm text-muted-foreground leading-relaxed">
                By accessing or using Klauza ("the Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the Service. We reserve the right to modify these Terms at any time, and your continued use constitutes acceptance of any changes.
              </p>
            </section>

            <section>
              <h2 className="font-display text-sm uppercase tracking-wider text-foreground mb-3">2. Important Disclaimer — Not a Law Firm</h2>
              <div className="p-4 rounded-lg bg-card border border-primary/30 mb-4">
                <p className="text-sm text-foreground leading-relaxed font-medium">
                  Klauza is a technology platform, not a law firm. We do not provide legal advice, legal representation, or attorney-client relationships. The contract analysis, demand letters, court information, and escalation tools provided by Klauza are self-help tools designed to assist freelancers in managing their business relationships.
                </p>
              </div>
              <p className="text-sm text-muted-foreground leading-relaxed">
                You are solely responsible for your own legal decisions. The demand letters and court preparation materials generated by the Service are templates and informational resources — they are not substitutes for professional legal counsel. We strongly recommend consulting with a licensed attorney for specific legal matters, particularly before filing claims in court.
              </p>
            </section>

            <section>
              <h2 className="font-display text-sm uppercase tracking-wider text-foreground mb-3">3. Account Responsibilities</h2>
              <p className="text-sm text-muted-foreground leading-relaxed">
                You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to provide accurate and complete information when creating your account and to update it as necessary. You must notify us immediately of any unauthorized use of your account.
              </p>
            </section>

            <section>
              <h2 className="font-display text-sm uppercase tracking-wider text-foreground mb-3">4. Subscription Plans & Billing</h2>
              <div className="space-y-3 text-sm text-muted-foreground leading-relaxed">
                <p>Klauza offers the following subscription plans:</p>
                <ul className="space-y-2">
                  <li className="flex items-start gap-2"><span className="text-primary mt-0.5">—</span> <strong>Free Plan:</strong> Limited access to core features with usage restrictions as displayed in the application.</li>
                  <li className="flex items-start gap-2"><span className="text-primary mt-0.5">—</span> <strong>Pro Plan ($80/month):</strong> Full access to all features including unlimited contracts, invoices, clients, and the Chase dispute engine.</li>
                  <li className="flex items-start gap-2"><span className="text-primary mt-0.5">—</span> <strong>Enterprise Plan ($350/month):</strong> Everything in Pro plus priority support, custom onboarding, and API access.</li>
                </ul>
                <p>
                  Subscriptions are billed monthly. You authorize us to charge your designated payment method on a recurring basis until you cancel. Prices are subject to change with 30 days' prior notice.
                </p>
              </div>
            </section>

            <section>
              <h2 className="font-display text-sm uppercase tracking-wider text-foreground mb-3">5. Cancellation & Refunds</h2>
              <p className="text-sm text-muted-foreground leading-relaxed">
                You may cancel your subscription at any time through your account settings. Upon cancellation, you will retain access to paid features until the end of your current billing period. No refunds are provided for partial billing periods. If you downgrade from a paid plan to the free plan, your access to premium features will end at the conclusion of the paid period.
              </p>
            </section>

            <section>
              <h2 className="font-display text-sm uppercase tracking-wider text-foreground mb-3">6. Acceptable Use</h2>
              <p className="text-sm text-muted-foreground leading-relaxed mb-3">
                You agree not to use the Service to:
              </p>
              <ul className="space-y-2 text-sm text-muted-foreground leading-relaxed">
                <li className="flex items-start gap-2"><span className="text-primary mt-0.5">—</span> Harass, threaten, or intimidate any person</li>
                <li className="flex items-start gap-2"><span className="text-primary mt-0.5">—</span> Submit fraudulent disputes or fabricate claims</li>
                <li className="flex items-start gap-2"><span className="text-primary mt-0.5">—</span> Upload malicious content, viruses, or harmful code</li>
                <li className="flex items-start gap-2"><span className="text-primary mt-0.5">—</span> Violate any applicable law or regulation</li>
                <li className="flex items-start gap-2"><span className="text-primary mt-0.5">—</span> Attempt to access other users' accounts or data</li>
                <li className="flex items-start gap-2"><span className="text-primary mt-0.5">—</span> Reverse-engineer, decompile, or disassemble the Service</li>
                <li className="flex items-start gap-2"><span className="text-primary mt-0.5">—</span> Use automated systems to scrape or extract data from the Service</li>
              </ul>
              <p className="text-sm text-muted-foreground leading-relaxed mt-3">
                Violation of these terms may result in immediate account suspension or termination.
              </p>
            </section>

            <section>
              <h2 className="font-display text-sm uppercase tracking-wider text-foreground mb-3">7. Intellectual Property</h2>
              <p className="text-sm text-muted-foreground leading-relaxed">
                The Service and its original content (excluding user-provided data), features, and functionality are owned by Klauza and are protected by copyright, trademark, and other intellectual property laws. You retain all ownership rights to the data you input into the Service, including contracts, invoices, and client information.
              </p>
            </section>

            <section>
              <h2 className="font-display text-sm uppercase tracking-wider text-foreground mb-3">8. Limitation of Liability</h2>
              <p className="text-sm text-muted-foreground leading-relaxed">
                To the maximum extent permitted by law, Klauza and its officers, directors, employees, and agents shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, business opportunities, or goodwill, arising from your use of or inability to use the Service. Our total liability for any claim arising from these Terms or the Service shall not exceed the amount you paid to Klauza in the twelve (12) months preceding the claim.
              </p>
            </section>

            <section>
              <h2 className="font-display text-sm uppercase tracking-wider text-foreground mb-3">9. Dispute Resolution</h2>
              <p className="text-sm text-muted-foreground leading-relaxed">
                Any dispute, claim, or controversy arising out of or relating to these Terms or the Service shall be resolved through binding arbitration administered by the American Arbitration Association (AAA) under its Commercial Arbitration Rules. The arbitration shall take place in a mutually agreed location or remotely. Each party shall bear its own costs, and the arbitrator's decision shall be final and binding. You agree to waive any right to a jury trial or to participate in a class action lawsuit.
              </p>
            </section>

            <section>
              <h2 className="font-display text-sm uppercase tracking-wider text-foreground mb-3">10. Termination</h2>
              <p className="text-sm text-muted-foreground leading-relaxed">
                We reserve the right to suspend or terminate your access to the Service at our sole discretion, without notice, for conduct that we determine violates these Terms or is harmful to other users, us, or third parties. Upon termination, your right to use the Service ceases immediately. Provisions that by their nature should survive termination shall survive, including ownership, warranty disclaimers, indemnity, and limitations of liability.
              </p>
            </section>

            <section>
              <h2 className="font-display text-sm uppercase tracking-wider text-foreground mb-3">11. Governing Law</h2>
              <p className="text-sm text-muted-foreground leading-relaxed">
                These Terms shall be governed by and construed in accordance with the laws of the State of Delaware, without regard to its conflict of law provisions.
              </p>
            </section>

            <section>
              <h2 className="font-display text-sm uppercase tracking-wider text-foreground mb-3">12. Contact</h2>
              <p className="text-sm text-muted-foreground leading-relaxed">
                If you have questions about these Terms of Service, contact us at:
              </p>
              <div className="mt-3 p-4 rounded-lg bg-card border border-border">
                <p className="text-sm font-medium">Klauza — Legal Team</p>
                <p className="text-sm text-muted-foreground mt-1">
                  Email: <a href="mailto:legal@klauza.com" className="text-primary hover:underline">legal@klauza.com</a>
                </p>
              </div>
            </section>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="py-10 px-6 border-t border-border">
        <div className="max-w-6xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <div className="w-5 h-5 rounded bg-primary flex items-center justify-center">
              <span className="text-primary-foreground font-bold text-[10px]">K</span>
            </div>
            <span className="font-display text-xs tracking-[0.2em]">KLAUZA</span>
          </div>
          <p className="text-xs text-muted-foreground">&copy; 2026 Klauza. All rights reserved.</p>
          <div className="flex items-center gap-4 text-xs text-muted-foreground">
            <Link href="/privacy" className="hover:text-foreground transition-colors">Privacy</Link>
            <Link href="/cookies" className="hover:text-foreground transition-colors">Cookies</Link>
            <Link href="/contact" className="hover:text-foreground transition-colors">Contact</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
